### ISSUE TITLE
运行起来后接口都是报错的

### ISSUE THREAD

**Issue by 13615817501** [jiangxin0816/vue-music#1]
![image](https://user-images.githubusercontent.com/23720587/39169658-42e1ffac-47cb-11e8-9ff6-e901452782fd.png)

**Comment by jy-scp** [comment]
请先clone这个api接口项目并运行：https://binaryify.github.io/NeteaseCloudMusicApi。
我在vue-cli里配置的接口是本地反向代理 :P
